### ISSUE TITLE
Add a new color theme

### ISSUE THREAD

**Issue by pandrei7** [pandrei7/personal_forum#3]
The application currently offers two preset themes: a light one and a dark one. We would like to add one more color theme to this list.

There aren't many restrictions for the new theme, but it should have decent contrast. You can use [this tool](https://webaim.org/resources/contrastchecker) (or other similar tools) to check the contrast.

You might find it easier to create the theme by using the "live preview" option. You can access it by clicking the `Customize` button in the theme selector. If you do this, you'll also be able to copy your colors from the browser's console.

Currently, the process of adding a new theme is a bit involved, so here are the steps:

1. Edit `templates/room.html.tera` to add a button for selecting your theme. Place it above the existing `Customize` button and give it the name of your theme (or a shorthand of it). Make sure to set a new ID for the button.
1. Edit `static/js/room.js`. Set the colors of your theme similar to the preset themes around line 646. The button should work now.
1. Style your button in `static/css/room.css`. Try to use colors from your theme for this.

**Comment by Rajeshwari-Jadhav** [comment]
Hi. Can this issue be assigned to me?

**Comment by pandrei7** [comment]
Hi! Sure, I'll assign it now.

**Comment by Rajeshwari-Jadhav** [comment]
Hi. I've made a PR. 
Please check it out.
